-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "unit" TEXT NOT NULL DEFAULT 'pcs',
ALTER COLUMN "stock" SET DEFAULT 0.0,
ALTER COLUMN "stock" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "minStockLevel" SET DEFAULT 5.0,
ALTER COLUMN "minStockLevel" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "StockLog" ALTER COLUMN "change" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "previous" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "current" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UdharItem" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;
